<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="16390" started-at="2020-12-16T06:42:29Z" finished-at="2020-12-16T06:42:45Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="16390" started-at="2020-12-16T06:42:29Z" finished-at="2020-12-16T06:42:45Z">
      <class name="testPages.FlipLoginTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:testPages.FlipLoginTest@20deea7f]" name="initialize" is-config="true" duration-ms="14713" started-at="2020-12-16T06:42:29Z" finished-at="2020-12-16T06:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="verifyLoginErrorMessage()[pri:0, instance:testPages.FlipLoginTest@20deea7f]" name="verifyLoginErrorMessage" duration-ms="16" started-at="2020-12-16T06:42:44Z" finished-at="2020-12-16T06:42:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at pageObjects.FlipLoginPage.getPopup(FlipLoginPage.java:36)
at testPages.FlipLoginTest.verifyLoginErrorMessage(FlipLoginTest.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginErrorMessage -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testPages.FlipLoginTest@20deea7f]" name="teardown" is-config="true" duration-ms="1575" started-at="2020-12-16T06:42:44Z" finished-at="2020-12-16T06:42:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testPages.FlipLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
